#!/usr/bin/env bash
# install-git-hooks.sh — wire project git hooks into .git/hooks.
#
# Idempotent. Run once per clone. If a matching hook already exists and
# isn't ours (no marker line), we back it up with .pre-alex-YYYYMMDD suffix
# before overwriting.
#
# Installed:
#   pre-commit → runs scripts/hooks/pre-commit-steps-check.js
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
HOOKS_DIR="$REPO_ROOT/.git/hooks"
MARKER="# alex-pre-commit-steps-check"

mkdir -p "$HOOKS_DIR"

TARGET="$HOOKS_DIR/pre-commit"

# Backup any existing non-ours hook
if [ -f "$TARGET" ] && ! grep -q "$MARKER" "$TARGET" 2>/dev/null; then
  BACKUP="$TARGET.pre-alex-$(date +%Y%m%d%H%M%S)"
  cp "$TARGET" "$BACKUP"
  echo "Backed up existing pre-commit → $BACKUP"
fi

cat > "$TARGET" <<'HOOK'
#!/usr/bin/env bash
# alex-pre-commit-steps-check
# Auto-generated by scripts/install-git-hooks.sh — safe to regenerate.
# Blocks commits that break docs/00-canonical/STEPS.json schema OR leave
# the canonical step-table docs drifted from STEPS.json.
set -e

REPO_ROOT=$(git rev-parse --show-toplevel)
SCRIPT="$REPO_ROOT/scripts/hooks/pre-commit-steps-check.js"

if [ ! -f "$SCRIPT" ]; then
  # If the validator is missing, don't block — warn and let the commit through.
  # (A fresh clone without scripts/ checked out should not be strangled.)
  echo "pre-commit: $SCRIPT missing — skipping steps check" >&2
  exit 0
fi

# Prefer node from PATH; give a clear error if absent.
if ! command -v node >/dev/null 2>&1; then
  echo "pre-commit: node not found on PATH — cannot validate STEPS.json" >&2
  exit 1
fi

exec node "$SCRIPT"
HOOK

chmod +x "$TARGET"
echo "Installed pre-commit → $TARGET"
echo "It runs node $REPO_ROOT/scripts/hooks/pre-commit-steps-check.js"
