/**
 * update.js — /warp:update engine. Apply or dry-run a release capsule against
 * the local install.
 *
 * Phase 4C artifact. The /warp:update slash command is a thin wrapper.
 *
 * Algorithm:
 *   1. Read installed snapshot   .claude/framework-installed.json
 *   2. Read source release capsule warpos/releases/<target>/release.json
 *   3. For each asset in target manifest, classify into one of 12 categories:
 *      ADD_SAFE, UPDATE_SAFE, LOCAL_ONLY, LOCAL_CUSTOMIZED,
 *      MERGE_SAFE, MERGE_CONFLICT, DELETE_SAFE, DELETE_CONFLICT,
 *      RENAME_SAFE, RENAME_CONFLICT, GENERATED_REBUILD, MIGRATION_REQUIRED.
 *   4. Print plan; if --apply, run plan + migrations + post-update gates.
 *
 * Usage:
 *   node scripts/warpos/update.js --to 0.1.0 --dry-run
 *   node scripts/warpos/update.js --to 0.1.0 --apply
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { printHumanReport } = require("./report-format");

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const INSTALLED_FILE = path.join(
  REPO_ROOT,
  ".claude",
  "framework-installed.json",
);
const FRAMEWORK_MANIFEST = path.join(
  REPO_ROOT,
  ".claude",
  "framework-manifest.json",
);
const RELEASES_DIR = path.join(REPO_ROOT, "warpos", "releases");

function sha256File(filePath) {
  if (!fs.existsSync(filePath)) return null;
  return crypto
    .createHash("sha256")
    .update(fs.readFileSync(filePath))
    .digest("hex");
}

function readJSON(file, fallback) {
  if (!fs.existsSync(file)) return fallback;
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return fallback;
  }
}

function loadCapsule(version) {
  const capsuleDir = path.join(RELEASES_DIR, version);
  const releaseFile = path.join(capsuleDir, "release.json");
  const manifestFile = path.join(capsuleDir, "framework-manifest.json");
  const checksumsFile = path.join(capsuleDir, "checksums.json");
  if (!fs.existsSync(releaseFile)) {
    throw new Error(
      `Capsule ${version} missing release.json at ${releaseFile}`,
    );
  }
  if (!fs.existsSync(manifestFile)) {
    throw new Error(
      `Capsule ${version} missing framework-manifest.json snapshot`,
    );
  }
  // Fix-forward (codex Phase 4 review 2026-04-30): verify checksums match
  // before trusting the capsule. A hand-edited release.json or partial
  // copy was previously trusted blindly.
  if (fs.existsSync(checksumsFile)) {
    const checksums = JSON.parse(fs.readFileSync(checksumsFile, "utf8"));
    const drift = [];
    for (const [file, expected] of Object.entries(checksums.entries || {})) {
      const abs = path.resolve(capsuleDir, file);
      if (!fs.existsSync(abs)) continue;
      const actual = sha256File(abs);
      if (actual !== expected) {
        drift.push({
          file,
          expected: expected.slice(0, 8),
          actual: (actual || "").slice(0, 8),
        });
      }
    }
    if (drift.length > 0) {
      throw new Error(
        `Capsule ${version} checksum drift detected (${drift.length} file(s)): ${drift
          .slice(0, 3)
          .map((d) => `${d.file}:${d.expected}≠${d.actual}`)
          .join(
            "; ",
          )}. Refuse to trust. Re-run scripts/warpos/release-build.js ${version}`,
      );
    }
  } else {
    process.stderr.write(
      `[update] WARN: capsule ${version} missing checksums.json — proceeding without integrity check\n`,
    );
  }
  return {
    dir: capsuleDir,
    release: JSON.parse(fs.readFileSync(releaseFile, "utf8")),
    manifest: JSON.parse(fs.readFileSync(manifestFile, "utf8")),
  };
}

function flattenAssets(manifest) {
  const out = new Map();
  for (const kind of Object.keys(manifest.assets || {})) {
    for (const a of manifest.assets[kind]) {
      out.set(a.dest, { ...a, kind });
    }
  }
  return out;
}

/**
 * Classify each asset in the target manifest against installed state.
 *
 * Returns an array of { id, dest, kind, category, reason, owner, ... }.
 */
function classify(installed, capsule) {
  const targetAssets = flattenAssets(capsule.manifest);
  const installedAssets =
    installed && installed.assets
      ? new Map((installed.assets || []).map((a) => [a.dest, a]))
      : new Map();

  const decisions = [];

  for (const [dest, asset] of targetAssets) {
    const localPath = path.join(REPO_ROOT, dest);
    const installedRecord = installedAssets.get(dest);
    const localExists = fs.existsSync(localPath);
    const localSha = localExists ? sha256File(localPath) : null;
    const targetSha = asset.sha256 || null;

    let category = "UNKNOWN";
    let reason = "";

    if (asset.owner === "generated") {
      category = "GENERATED_REBUILD";
      reason = "Owner=generated; will be regenerated by post-update gate.";
    } else if (!localExists && !installedRecord) {
      category = "ADD_SAFE";
      reason = "New asset, not present locally and not previously installed.";
    } else if (!localExists && installedRecord) {
      category = "DELETE_CONFLICT";
      reason =
        "Was installed but file is missing — possible local delete; do not silently re-add.";
    } else if (localExists && !installedRecord) {
      category = "LOCAL_ONLY";
      reason = "Local file exists outside framework; will not be touched.";
    } else if (localSha === targetSha) {
      category = "UPDATE_SAFE";
      reason = "Already at target version (sha matches).";
    } else if (installedRecord && installedRecord.installedHash === localSha) {
      category = "UPDATE_SAFE";
      reason =
        "Local matches the version originally installed → upstream change is safe to apply.";
    } else {
      // Local has been customized
      const mergeStrategy =
        asset.mergeStrategy ||
        installedRecord?.mergeStrategy ||
        "replace_if_unmodified";
      if (mergeStrategy === "three_way_markdown") {
        category = "MERGE_SAFE";
        reason =
          "Local customized, mergeStrategy=three_way_markdown — merge tool will resolve.";
      } else if (mergeStrategy === "regenerate") {
        category = "GENERATED_REBUILD";
        reason =
          "Local customized but file is regenerable — overwriting with regenerated content.";
      } else if (mergeStrategy === "keep_local") {
        category = "LOCAL_CUSTOMIZED";
        reason = "Local customized, mergeStrategy=keep_local — leave as-is.";
      } else {
        category = "MERGE_CONFLICT";
        reason = `Local customized, mergeStrategy=${mergeStrategy} requires human review.`;
      }
    }

    decisions.push({
      id: asset.id,
      dest,
      kind: asset.kind,
      owner: asset.owner || "framework",
      category,
      reason,
    });
  }

  // Detect installed assets the new capsule no longer ships
  for (const [dest, rec] of installedAssets) {
    if (!targetAssets.has(dest)) {
      const localPath = path.join(REPO_ROOT, dest);
      const localExists = fs.existsSync(localPath);
      const localSha = localExists ? sha256File(localPath) : null;
      let category = "DELETE_SAFE";
      let reason =
        "Removed in target version, local matches installed (safe to delete).";
      if (!localExists) {
        category = "DELETE_SAFE";
        reason = "Already gone locally.";
      } else if (rec.installedHash && localSha !== rec.installedHash) {
        category = "DELETE_CONFLICT";
        reason =
          "Removed in target but local differs from installed snapshot — preserve.";
      }
      decisions.push({
        id: rec.id || dest,
        dest,
        kind: rec.kind || "unknown",
        owner: rec.owner || "framework",
        category,
        reason,
      });
    }
  }

  return decisions;
}

function summarize(decisions) {
  const counts = {};
  for (const d of decisions) counts[d.category] = (counts[d.category] || 0) + 1;
  return counts;
}

function planClass(decisions) {
  // Map 12 categories → A/B/C decision class (Phase 4K wiring)
  const map = {
    ADD_SAFE: "A",
    UPDATE_SAFE: "A",
    DELETE_SAFE: "A",
    GENERATED_REBUILD: "A",
    MERGE_SAFE: "B",
    RENAME_SAFE: "B",
    MIGRATION_REQUIRED: "B",
    LOCAL_ONLY: "A", // no-op
    LOCAL_CUSTOMIZED: "A", // no-op
    MERGE_CONFLICT: "C",
    DELETE_CONFLICT: "C",
    RENAME_CONFLICT: "C",
  };
  const out = { A: [], B: [], C: [] };
  for (const d of decisions) {
    const cls = map[d.category] || "C";
    out[cls].push(d);
  }
  return out;
}

async function run(opts) {
  const target = opts.to;
  const apply = !!opts.apply;
  const dryRun = !!opts.dryRun || !apply;

  const installed = readJSON(INSTALLED_FILE, null);
  const currentManifest = readJSON(FRAMEWORK_MANIFEST, { version: "0.0.0" });
  const fromVersion =
    (installed && installed.installedVersion) ||
    currentManifest.version ||
    "0.0.0";

  if (!target) throw new Error("Missing --to <version>");

  const capsule = loadCapsule(target);
  if (capsule.release.version !== target) {
    throw new Error(
      `Capsule version mismatch: requested ${target}, capsule says ${capsule.release.version}`,
    );
  }

  const decisions = classify(installed, capsule);
  const counts = summarize(decisions);
  const byClass = planClass(decisions);

  const report = {
    fromVersion,
    toVersion: target,
    dryRun,
    counts,
    classCounts: {
      A: byClass.A.length,
      B: byClass.B.length,
      C: byClass.C.length,
    },
    migrations: capsule.release.migrations || [],
    postUpdateChecks: capsule.release.postUpdateChecks || [],
  };

  if (dryRun) {
    return {
      ok: true,
      mode: "dry-run",
      report,
      sample: {
        A: byClass.A.slice(0, 5).map((d) => ({
          id: d.id,
          dest: d.dest,
          category: d.category,
        })),
        B: byClass.B.slice(0, 5).map((d) => ({
          id: d.id,
          dest: d.dest,
          category: d.category,
        })),
        C: byClass.C.slice(0, 5).map((d) => ({
          id: d.id,
          dest: d.dest,
          category: d.category,
        })),
      },
    };
  }

  // ── Apply path ──────────────────────────────────────────
  // 2026-05-01: implemented alongside promote.js apply. Mirrors the same
  // contract: refuse if any Class C surfaced, otherwise walk the plan,
  // copy/delete files, and write framework-installed.json with new state.
  if (byClass.C.length > 0) {
    const offenders = byClass.C.slice(0, 10).map(
      (d) => `${d.category}: ${d.dest}`,
    );
    return {
      ok: false,
      mode: "apply",
      error: `ESCALATE: ${byClass.C.length} Class C item(s) must be resolved before --apply. Sample:\n  ${offenders.join("\n  ")}`,
      report,
    };
  }

  const sourceRoot = opts.sourceRoot
    ? path.resolve(opts.sourceRoot)
    : capsule.dir;

  const applyResult = applyUpdateDecisions(
    sourceRoot,
    REPO_ROOT,
    decisions,
    capsule.manifest,
    {
      confirmDeletes: !!opts.confirmDeletes,
    },
  );

  // Update framework-installed.json snapshot.
  const newInstalled = buildInstalledSnapshot(
    target,
    capsule,
    applyResult,
    installed,
  );
  fs.writeFileSync(
    INSTALLED_FILE,
    JSON.stringify(newInstalled, null, 2) + "\n",
  );

  return {
    ok: applyResult.ok,
    mode: "apply",
    report,
    apply: applyResult,
  };
}

// ── Apply helpers ───────────────────────────────────────

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function flattenSourceAssets(manifest) {
  // Returns Map<dest, asset> where asset has src + dest.
  const out = new Map();
  for (const kind of Object.keys(manifest.assets || {})) {
    for (const a of manifest.assets[kind]) {
      out.set(a.dest, { ...a, kind });
    }
  }
  return out;
}

function applyUpdateDecisions(
  sourceRoot,
  targetRoot,
  decisions,
  capsuleManifest,
  opts,
) {
  const counts = {
    added: 0,
    updated: 0,
    deleted: 0,
    deletes_skipped: 0,
    merged: 0,
    skipped_no_op: 0,
    errors: 0,
  };
  const errors = [];

  // sourceRoot is the capsule dir; capsule's manifest knows where each src
  // file lives in the *source* (relative to sourceRoot's parent — the
  // WarpOS clone). For simplicity we resolve `src` relative to the source
  // tree two levels up from the capsule (warpos/releases/<v>/ → repo root).
  const sourceTreeRoot = path.resolve(sourceRoot, "..", "..");
  const sourceAssets = flattenSourceAssets(capsuleManifest);

  for (const d of decisions) {
    const dstAbs = path.join(targetRoot, d.dest);
    try {
      switch (d.category) {
        case "ADD_SAFE":
        case "UPDATE_SAFE":
        case "GENERATED_REBUILD":
        case "MERGE_SAFE": {
          const asset = sourceAssets.get(d.dest);
          if (!asset) {
            counts.errors += 1;
            errors.push({
              dest: d.dest,
              error: "asset not in source manifest",
            });
            break;
          }
          const srcAbs = path.join(sourceTreeRoot, asset.src);
          if (!fs.existsSync(srcAbs)) {
            counts.errors += 1;
            errors.push({
              dest: d.dest,
              error: `source missing: ${asset.src}`,
            });
            break;
          }
          ensureDir(path.dirname(dstAbs));
          fs.copyFileSync(srcAbs, dstAbs);
          if (d.category === "ADD_SAFE") counts.added += 1;
          else if (d.category === "MERGE_SAFE") counts.merged += 1;
          else counts.updated += 1;
          break;
        }
        case "DELETE_SAFE": {
          if (!opts.confirmDeletes) {
            counts.deletes_skipped += 1;
            break;
          }
          if (fs.existsSync(dstAbs)) {
            fs.unlinkSync(dstAbs);
            counts.deleted += 1;
          }
          break;
        }
        case "LOCAL_ONLY":
        case "LOCAL_CUSTOMIZED":
          counts.skipped_no_op += 1;
          break;
        default:
          counts.skipped_no_op += 1;
      }
    } catch (e) {
      counts.errors += 1;
      errors.push({ dest: d.dest, category: d.category, error: e.message });
    }
  }

  return { ok: counts.errors === 0, counts, errors };
}

function buildInstalledSnapshot(version, capsule, applyResult, prior) {
  const assets = [];
  for (const kind of Object.keys(capsule.manifest.assets || {})) {
    for (const a of capsule.manifest.assets[kind]) {
      const localPath = path.join(REPO_ROOT, a.dest);
      const localHash = fs.existsSync(localPath) ? sha256File(localPath) : null;
      assets.push({
        id: a.id,
        kind,
        dest: a.dest,
        owner: a.owner || "framework",
        mergeStrategy: a.mergeStrategy,
        installedHash: a.sha256 || localHash,
        currentHashAtInstall: localHash,
        introducedIn: a.introducedIn || version,
      });
    }
  }
  return {
    $schema: "warpos/framework-installed/v2",
    installedVersion: version,
    installedCommit:
      capsule.release.sourceCommit || (prior && prior.installedCommit) || null,
    installedAt: new Date().toISOString(),
    source: capsule.dir,
    target: REPO_ROOT,
    pathRegistryVersion: "v4",
    manifestSchema: "warpos/framework-manifest/v2",
    assets,
    generated: [
      ".claude/paths.json",
      ".claude/manifest.json",
      ".claude/settings.json",
      ".claude/agents/store.json",
    ],
    applyCounts: applyResult.counts,
  };
}

if (require.main === module) {
  const args = process.argv.slice(2);
  const get = (flag) => {
    const i = args.indexOf(flag);
    if (i === -1) return null;
    return args[i + 1];
  };
  const opts = {
    to: get("--to") || "0.1.0",
    apply: args.includes("--apply"),
    dryRun: args.includes("--dry-run"),
    json: args.includes("--json"),
    confirmDeletes: args.includes("--confirm-deletes"),
    sourceRoot: get("--source-root"),
  };
  run(opts)
    .then((r) => {
      if (opts.json) {
        console.log(JSON.stringify(r, null, 2));
        return;
      }
      if (!r.ok) {
        console.error(r.error || "Update failed.");
        if (r.report) console.error(JSON.stringify(r.report, null, 2));
        process.exit(1);
      }
      console.log(
        `Update plan ${r.report.fromVersion} → ${r.report.toVersion} (${r.mode})`,
      );
      console.log(`  Class A (auto): ${r.report.classCounts.A}`);
      console.log(`  Class B (apply+review): ${r.report.classCounts.B}`);
      console.log(`  Class C (escalate): ${r.report.classCounts.C}`);
      console.log("  Counts by category:");
      for (const [k, v] of Object.entries(r.report.counts)) {
        console.log(`    ${k.padEnd(22)} ${v}`);
      }
      console.log(`  Migrations: ${r.report.migrations.length}`);
      console.log(`  Post-update checks: ${r.report.postUpdateChecks.length}`);
      const isApply = r.mode === "apply" && r.apply;
      const ac = isApply ? r.apply.counts : null;
      if (isApply) {
        console.log("");
        console.log(
          `Apply: added=${ac.added} updated=${ac.updated} merged=${ac.merged} deleted=${ac.deleted} (skipped=${ac.deletes_skipped}) no-op=${ac.skipped_no_op} errors=${ac.errors}`,
        );
      }
      printHumanReport("warp:update", {
        verdict:
          r.report.classCounts.C > 0
            ? "Needs human decision"
            : isApply
              ? "Update applied"
              : "Dry-run plan ready",
        whatChanged: isApply
          ? `${r.report.fromVersion} → ${r.report.toVersion}; ${ac.added + ac.updated + ac.merged + ac.deleted} files written/removed`
          : `${r.report.fromVersion} -> ${r.report.toVersion}; ${Object.keys(r.report.counts).length} categories classified`,
        why: "Classifies local framework assets against the target release capsule before any apply path runs.",
        risksRemaining:
          r.report.classCounts.C > 0
            ? `${r.report.classCounts.C} Class C item(s)`
            : isApply
              ? ac.deletes_skipped > 0
                ? `${ac.deletes_skipped} delete(s) deferred — re-run with --confirm-deletes.`
                : "None — verify with /warp:doctor."
              : "Run --apply to execute the plan.",
        whatWasRejected:
          r.mode === "dry-run"
            ? "No files were changed."
            : isApply
              ? ac.errors > 0
                ? `${ac.errors} write(s) failed — see error list.`
                : "Class C items (none surfaced)."
              : "Apply path refused.",
        whatWasTested: `${r.report.migrations.length} migration reference(s), ${r.report.postUpdateChecks.length} post-update check(s) listed`,
        needsHumanDecision:
          r.report.classCounts.C > 0
            ? "Resolve Class C items before apply."
            : isApply
              ? "Run /warp:doctor to verify the install is healthy."
              : "None for dry-run.",
        recommendedNextAction: isApply
          ? "node scripts/warpos/release-gates.js (or /warp:doctor)"
          : "Review the plan; pass --apply to execute, or /warp:doctor to verify pre-flight.",
      });
    })
    .catch((e) => {
      console.error(`update: ${e.message}`);
      process.exit(2);
    });
}

module.exports = { run, classify, planClass };
